version: '3.7'
networks:
  portal-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - portal-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "UserPortalTopic:1:1,ManagementTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - portal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  management:
    container_name: management-grpc
    image: management/grpc:lastest
    build:
      context: .
      dockerfile: /Management/Dockerfile
    ports:
     - "8082:80"
    environment:
        KAFKA_CONNECT: kafka:9092
    depends_on:
        - kafka
    networks:
      - portal-network

  userportal:
    container_name: userportal-webapi
    image: userportal/webapi:lastest
    build:
      context: .
      dockerfile: /UserPortal/Dockerfile
    ports:
     - "8081:80"
    environment:
        DB_CONNECTION_STRING: "host=db;username=postgres;password=123456;port=5432;database=PORTAL;"
        KAFKA_CONNECT: kafka:9092
    depends_on:
        - db
        - kafka
    networks:
      - portal-network

  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    ports:
      - 8099:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "PORTAL"
    networks:
      - portal-network

